# Write a one-line Python generator or iterator expression that returns the 
# sequence of increasing integers generated by repeatedly adding the ascii 
# values of each letter in the word “Close” to itself. 67, 175, 286, 
# 84336, 39331, 49765, 12449, 49371, 58299, 81826 are a sample from this series.
#  Assume any needed Python standard library modules are already imported.

d = [
    67,
    108,
    111,
    115,
    101,
]

c= ['C','l','o ','s','e']

def close_generator() -> int:
    sum,C,l,o,s,e = 0, 67,108,111,115,101
    while True:
        yield sum
        sum+=C



sum =0
sum = close_generator()
counter =0
for i in close_generator():
    print(next(sum))
    counter +=1
    if counter>10:
        break


